[package]
name = "esp-riscv-rt"
version = "0.11.0"
edition = "2024"

[dependencies]
riscv-rt-macros = { version = "0.4.0", path = "../../riscv/riscv-rt/macros" }
defmt           = { version = "0.3.10", optional = true }

[features]
## Indicate that the device supports `mie` and `mip` instructions.
# esp32c3 has no standalone mie and mip registers, but only a mie bit in mstatus
has-mie-mip = []
## Indicate that the device has RTC RAM.
# we are not using esp32c3 RTC FAST Memory yet
rtc-ram = []

defmt = ["dep:defmt"]
