[device]
name  = "esp32c3"
arch  = "riscv"
cores = "single_core"

peripherals = [
    # Peripherals available in the PAC:
    "efuse",
    "gpio",
    "interrupt_core0",
    "rng",
    "rtc_cntl",
    "system",
    "systimer",
    "timg0",
    "uart1",
]

symbols = [
    # Additional peripherals defined by us (the developers):
    "phy",
    "wifi",
]
 
memory = [{ name = "dram", start = 0x3FC8_0000, end = 0x3FCE_0000 }]
