/*
ESP32C3 ECO3 ROM address table
Version 3 API's imported from the ROM
*/

/* 8 */
/*lmacTxDone = 0x4000162c;*/
/* 9 */
/*ppMapTxQueue = 0x400016d8;*/
/* 10 */
/*rcGetSched = 0x40001764;*/


/* 37 */
/***************************************
   Group eco3_wifi
 ***************************************/

/* 41 */
/* Functions */
/* 42 */
wdev_is_data_in_rxlist = 0x40001b2c;
/* 43 */
ppProcTxCallback = 0x40001b30;
/* 44 */
ieee80211_gettid = 0x40001b34;