[package]
name = "ecu-via-elm327"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ecu-via-elm327"
path = "src/main.rs"
test = false
bench = false
doctest = false

[profile.release]
debug = 0           # Set to 0 to prevent frame pointer preservation for debugging
opt-level = "s"     # "s" or "z" for size optimizations often helps elision
                    # this is what really removes frame pointers (about 8K savings)

[dependencies]
esp-println = { version = "0.16.0", default-features = false }
#esp-println = { version = "0.16.0", default-features = false, features = ["critical-section"] }
esp-backtrace = { version = "0.18.0",features = ["panic-handler"], optional = true }
defmt = { version = "1.0.1", optional = true }
log = { version = "0.4.14", optional = true }
esp-hal = { path = "../../esp-hal/esp-hal", default-features = false, features = ["rt"]}
#esp-hal = { version = "1.0.0", default-features = false, features = ["requires-unstable"] }
cfg-if = "1.0.0"
esp-alloc = { version = "0.9.0", default-features = false }
strum_macros = "0.27"

#esp-hal-embassy = { path = "../../esp-hal/esp-hal-embassy"  }
embassy-executor = { path = "../../embassy/embassy-executor.me" }
# although we don't plan to use "dhcpv4" feature we define it
# since it products less code in icmp and udp because we can implement only "icmp echo" 
embassy-net = { path =  "../../embassy/embassy-net", features = ["udp", "dhcpv4"]}
embassy-time = { path = "../../embassy/embassy-time" }
#embassy-sync = { path = "../../embassy/embassy-sync" }
#embassy-sync = { path = "../../embassy/embassy-sync.me" }
embassy-sync = "0.7"
embassy-futures = { path = "../../embassy/embassy-futures" }
#esp-wifi = { path = "../../esp-hal/esp-wifi", features = ["wifi"] }
esp-radio = { path = "../../esp-hal/esp-radio", features = ["wifi"] }
esp-rtos = { path = "../../esp-hal/esp-rtos", features = ["esp-radio", "embassy", "esp-alloc"] }
esp-bootloader-esp-idf = { path = "../../esp-hal/esp-bootloader-esp-idf.me" }

[features]
default = [
    "esp32c3",
    "defmt",
    "ecu",
]

esp32c3 = [
    "esp-println/esp32c3",
    "esp-println/jtag-serial",
    "esp-backtrace?/esp32c3",
    "esp-hal/esp32c3",
    "esp-hal/rt",
    #"esp-hal/unstable",
    #"esp-hal-embassy/esp32c3",
    "embassy-executor/nightly",     # for 'task' embassy-executor-macro
    #"esp-wifi/esp32c3",
    "esp-radio/esp32c3",
    "esp-rtos/esp32c3",
]

defmt = [
    "dep:defmt",
    "esp-println/defmt-espflash",
    "esp-backtrace?/defmt",
    "esp-hal/defmt",
    #"esp-hal-embassy/defmt",
    "embassy-executor/defmt",
    "embassy-time/defmt",
    "embassy-time/defmt-timestamp-uptime",
    #"esp-wifi/defmt",
    "esp-radio/defmt",
    "esp-rtos/defmt",
    "embassy-net/defmt",
    "embassy-futures/defmt",
]

backtrace = ["dep:esp-backtrace"]       # needs "-C", "force-frame-pointers" rustflag in config.toml
                                        # needs to comment build-std-features = ["panic_immediate_abort"] out                                        

## ECU related features
##
# supported ECUs
ccm450 = ["elm327", "kwp2000"]

# ECU adapters
elm327 = []
l9637 = []

# ECU protocols
kwp2000 = []

# selected ECU
ecu = ["ccm450"]

[build-dependencies]
esp-config = { version = "0.6.1", features = ["build"] }
esp-metadata-generated = { version = "0.3.0", features = ["build-script"] }