[package]
name = "ecu-via-elm327"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "ecu-via-elm327"
path = "src/main.rs"
test = false
bench = false
doctest = false

[profile.release]
# this following two needs for the minimum size for panic_immediate_abort
lto = "fat"         # Allows the compiler to see across crate boundaries
opt-level = "s"     # "s" or "z" for size optimizations often helps elision
                    # this is what really removes frame pointers

#debug = 0          # Set to 0 to prevent frame pointer preservation for debugging
#panic = "abort"
#codegen-units = 1   # Maximizes the chance to delete unused strings
#strip = "debuginfo" # Removes remaining symbol table entries

[dependencies]
esp-println = { version = "0.16.0", default-features = false, features = ["critical-section"] }
esp-backtrace = { version = "0.18.0", features = ["panic-handler"], optional = true }
defmt = { version = "1.0.1", optional = true }
log = { version = "0.4.14", optional = true }
esp-hal = { version = "1.0.0", features = ["unstable"] }
cfg-if = "1.0.0"
esp-alloc = { version = "0.9.0", default-features = false }
strum_macros = "0.27"

embassy-executor = "0.9.0"
# although we don't plan to use "dhcpv4" feature we define it
# since it products less code in icmp and udp because we can implement only "icmp echo" 
embassy-net = { version = "0.7.1", features = ["udp", "dhcpv4"]}
embassy-time = "0.5.0"
embassy-sync = "0.7"
embassy-futures = "0.1.2"
esp-radio = { version = "0.17.0", features = ["wifi", "no_wpa_supplicant"] }
esp-rtos = { version = "0.2.0", features = ["esp-radio", "embassy", "esp-alloc"] }
esp-bootloader-esp-idf = "0.4.0"

rtos-trace = { version = "0.2.1", optional = true }
rtt-target = { version = "0.6.2", optional = true }
systemview-target = { version = "0.3", optional = true, default-features = false, features = ["ext-rtt-channels-2"] }

[features]
default = [
    "esp32c3",
    "defmt",
    "ecu",
]

esp32c3 = [
    "esp-println/esp32c3",
    "esp-println/jtag-serial",
    "esp-backtrace?/esp32c3",
    "esp-bootloader-esp-idf/esp32c3",
    "esp-hal/esp32c3",
    "esp-hal/rt",
    "embassy-executor/nightly",     # for 'task' embassy-executor-macro
    "esp-radio/esp32c3",
    "esp-rtos/esp32c3",
]

defmt = [
    "dep:defmt",
    "esp-backtrace?/defmt",
    "esp-bootloader-esp-idf/defmt",
    "esp-hal/defmt",
    "embassy-executor/defmt",
    "embassy-time/defmt",
    "embassy-time/defmt-timestamp-uptime",
    "esp-radio/defmt",
    "embassy-net/defmt",
    "embassy-futures/defmt",
    "esp-rtos/defmt",

    #"esp-println/defmt-espflash",       # if you use rtt (rtt_target) it should be commented out
                                        # since rtt-target/defmt also defines defmt symbols
    "rtt-target?/defmt",
    "esp-alloc/defmt",
]

backtrace = ["dep:esp-backtrace"]       # needs "-C", "force-frame-pointers" rustflag in config.toml
                                        # needs to comment build-std-features = ["panic_immediate_abort"] out

## ECU related features
##
# supported ECUs
ccm450 = ["elm327", "kwp2000"]

# ECU adapters
elm327 = []
l9637 = []

# ECU protocols
kwp2000 = []

# selected ECU
ecu = ["ccm450"]

rtos-trace = ["esp-rtos/rtos-trace", "dep:rtos-trace", "dep:systemview-target", "rtt"]
rtt = ["dep:rtt-target"]                   # "esp-println/defmt-espflash" should be commented out

## My custom features (some of them needs esp-hal patches)
heap_stats = ["esp-alloc/internal-heap-stats"]
idle_stats = ["esp-rtos/idle_stats"]
dump_packets_pretty = ["esp-radio/dump_packets_pretty"]     # it does not need ESP_RADIO_CONFIG_DUMP_PACKETS=true
                                                            # that env var dumps raw packets (for e.g. WireShark)
                                                            # this feature traces formatted packets
                                                            # both of them needs esp-radio= info (as minimal)
no-wpa-supplicant = []      # ap only configuration -> no wpa-supplicant needed 
                            # we can save 2K space

[build-dependencies]
esp-config = { version = "0.6.1", features = ["build"] }
esp-metadata-generated = { version = "0.3.0", features = ["build-script"] }
