[package]
name = "embassy-executor"
version = "0.9.0"
edition = "2021"

[lib]
test = false
bench = false

[dependencies]
defmt = { version = "1.0.1", optional = true }
log = { version = "0.4.14", optional = true }
critical-section = { version = "1.1" }
embassy-executor-macros = { path = "../embassy-executor-macros.me" }
embassy-executor-timer-queue = { path = "../embassy-executor-timer-queue" }
portable-atomic = { version = "1.5", optional = true }

[features]
default = ["executor-thread"]

## Enable nightly-only features
nightly = ["embassy-executor-macros/nightly"]

#! ### Executor

## Enable the thread-mode executor (using WFE/SEV in Cortex-M, WFI in other embedded archs)
executor-thread = []
## Enable the interrupt-mode executor (available in Cortex-M only)
executor-interrupt = []
## Enable tracing support (adds some overhead)
trace = []

_timer-item-payload = [] # A size was picked

arch-avr = []
