[package]
name = "riscv"
version = "0.15.1"
edition = "2021"

[lib]
test = false
bench = false

[dependencies]
riscv-pac = { path = "../riscv-pac.me", version = "0.2.0" }
defmt = { version = "0.3.10", optional = true }
critical-section = "1.2.0"

[features]
defmt = ["dep:defmt", "riscv-pac/defmt"]
s-mode = []

critical-section-single-hart = ["critical-section/restore-state-bool"]
