[package]
name = "esp-hal-embassy"
version = "0.8.0"
edition = "2024"

[dependencies]
console = { path = "../../console", features = ["usb_uart"]}
defmt = { version = "0.3.10", optional = true }
critical-section = { version = "1.2.0" }
esp-hal = { path = "../esp-hal" }
macros = { features = ["embassy"], package = "esp-hal-procmacros", path = "../esp-hal-procmacros" }
embassy-executor = { path = "../../embassy/embassy-executor" }
embassy-time-driver = { path = "../../embassy/embassy-time-driver", features = [ "tick-hz-1_000_000" ] }

[build-dependencies]
esp-build    = { path = "../esp-build" }
esp-metadata = { path = "../esp-metadata" }

[features]
esp32   = ["esp-hal/esp32"]
esp32c2 = ["esp-hal/esp32c2"]
esp32c3 = ["esp-hal/esp32c3"]
esp32c6 = ["esp-hal/esp32c6"]
esp32h2 = ["esp-hal/esp32h2"]
esp32s2 = ["esp-hal/esp32s2"]
esp32s3 = ["esp-hal/esp32s3"]
