[build]
target = "riscv32imc-unknown-none-elf"

[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"

rustflags = [
    "-C", "link-arg=-Tlinkall.x",           # from esp-hal
    "-C", "link-arg=-Map=riscv32.map",
]

[unstable]
# this will codegen every panic as an abort instruction without any panic message formatting.
#build-std-features = ["panic_immediate_abort"]
# build core from source with "panic_immediate_abort" feature
#build-std = ["core"]
