[package]
name = "embassy-net"
version = "0.7.0"
edition = "2021"

[dependencies]
console = { path = "../../console", features = ["usb_uart"]}
defmt = { version = "0.3.10", optional = true }
embassy-net-driver = { path = "../embassy-net-driver" }
embassy-time = { path = "../embassy-time" }
embassy-sync = { path = "../embassy-sync" }
smoltcp = { path = "../../smoltcp/smoltcp", default-features = false, features = ["socket", "async"] }
allocator-api2 = { path = "../../allocator-api2", features = ["alloc"] }

[features]
defmt = ["dep:defmt", "embassy-net-driver/defmt", "smoltcp/defmt"]

## Enable DNS support
dns = []
## Enable DHCPv4 support
dhcpv4 = ["proto-ipv4", "medium-ethernet", "smoltcp/socket-dhcpv4"]
## Enable DHCPv4 support with hostname
dhcpv4-hostname = ["dhcpv4"]
## Enable IPv4 support
proto-ipv4 = ["smoltcp/proto-ipv4"]
## Enable IPv6 support
proto-ipv6 = ["smoltcp/proto-ipv6"]
## Enable the Ethernet medium
medium-ethernet = ["smoltcp/medium-ethernet"]
## Enable smoltcp alloc feature (necessary if using "managed" crate alloc feature)
alloc = ["smoltcp/alloc"]