[workspace]
resolver = "2"
exclude  = [
    "esp-backtrace",
    "esp-build",
    "esp-hal",
    "esp-hal-embassy",
    "esp-hal-procmacros",
    "esp-metadata",
    "esp-println",
    "esp-riscv-rt",
]
