[workspace]
resolver = "2"
exclude  = [
    "esp-alloc",
    "esp-backtrace.me",
    "esp-config.me",
    "esp-hal",
    "esp-hal-embassy",
    "esp-hal-procmacros",
    "esp-metadata.me",
    "esp-riscv-rt",
    "esp-wifi",
]
