[package]
name = "esp-alloc"
version = "0.8.0"
edition = "2024"

[lib]
test = false

[dependencies]
#console = { path = "../../console" }
#defmt = { version = "0.3.10", optional = true }
defmt  = { version = "1.0.1", optional = true }
critical-section = { version = "1.2.0" }
#linked-list-allocator = { path = "../../linked-list-allocator" }
linked_list_allocator = { version = "0.10.5", default-features = false, features = ["const_mut_refs"] }
allocator-api2 = { path = "../../allocator-api2", features = ["alloc"]}

[features]

## Enable this feature if you want to keep stats about the internal heap usage such as:
## - Max memory usage since initialization of the heap
## - Total allocated memory since initialization of the heap
## - Total freed memory since initialization of the heap
##
## ⚠️ Note: Enabling this feature will require extra computation every time alloc/dealloc is called.
internal-heap-stats = []

defmt = ["dep:defmt", "allocator-api2/defmt"]
