[package]
name = "esp-phy"
version = "0.1.0"
edition = "2024"

[lib]
test = false
bench = false

[dependencies]
esp-hal = { path = "../esp-hal", default-features = false, features = ["rt"]}
esp-sync = "0.1.0"
esp-wifi-sys-esp32c3 = { path = "../../esp-wifi-sys" }
esp-metadata-generated = "0.3.0"

[build-dependencies]
esp-config = { version = "0.6.1", features = ["build"] }
esp-metadata-generated = { version = "0.3.0", features = ["build-script"] }

[features]
esp32c3 = ["esp-hal/esp32c3", "esp-wifi-sys-esp32c3/esp32c3"]