[package]
name = "embassy-executor-timer-queue"
version = "0.1.0"
edition = "2024"

[dependencies]

[features]
#! ### Timer Queue Item Size
#! Sets the size of the timer items.

## 4 words
timer-item-size-4-words = []

## 6 words
timer-item-size-6-words = []

## 8 words
timer-item-size-8-words = []
