[build]
target = "xtensa-esp32s3-none-elf"

[target.'cfg(all())']
rustflags = [
    "-C", "link-arg=-Tdefmt.x",             # for defmt
    "-C", "force-frame-pointers",           # for esp-backtrace and probe-rs-debug
                                            # otherwise some size ovehead occurs (in ELF file only)
                                            # when making frame for every real (not inlined) function call
                                            # it's not relevant, esp-backtrace uses frame pointers to walk
                                            # the stack easily and with low overhead, 

    #"-Z", "location-detail=none",           # Removes file, line, and column metadata

    # convert any panic (unwrap) into "noop/unimp", even before panic message formatting
    # even the core::slice::index::slice_index_fail and esp_hal::fmt::__unwrap_failed will be "noop/unimp"
    #"-C", "panic=immediate-abort",
    #"-Z", "unstable-options",               # this needs for panic-immediate-abort
]

[target.riscv32imc-unknown-none-elf]
#runner = "espflash flash --monitor"

# using defmt crate - together with "link-arg=-Tdefmt.x" above
runner = "espflash flash --monitor --log-format defmt"

rustflags = [
    "-C", "link-arg=-Tlinkall_debug.x",     # my master linker script
    "-C", "link-arg=-Map=esp32c3.map",
]

[target.xtensa-esp32-none-elf]
#runner = "espflash flash --baud 460800 --monitor"

# using defmt crate - together with "link-arg=-Tdefmt.x" above
runner = "espflash flash --monitor --baud 460800 --log-format defmt"

linker = "ldproxy"

rustflags = [
    "-C", "link-arg=-Tlinkall.x",          # esp-hal master linker script
    "-C", "linker=xtensa-esp32-elf-gcc",
    "-C", "llvm-args=--mtext-section-literals",
    "-C", "link-arg=-Wl,-Map=esp32.map",
]

[target.xtensa-esp32s3-none-elf]
#runner = "espflash flash --monitor"

# using defmt crate - together with "link-arg=-Tdefmt.x" above
runner = "espflash flash --monitor --log-format defmt"

# flash only, reset button or power off/on needed to start
#runner = "espflash flash --non-interactive --no-reset"

rustflags = [
    "-C", "link-arg=-Tlinkall.x",          # esp-hal master linker script
    "-C", "link-arg=-Wl,-Map=esp32s3.map",
]

[unstable]
build-std = ["core", "alloc"]

[patch.crates-io]
#esp-alloc = { git = "https://github.com/gobftald/esp-hal.git", branch = "patches" }
#esp-backtrace = { git = "https://github.com/gobftald/esp-hal.git", branch = "patches" }
#esp-bootloader-esp-idf = { git = "https://github.com/gobftald/esp-hal.git", branch = "patches" }
#esp-config = { git = "https://github.com/gobftald/esp-hal.git", branch = "patches" }
#esp-hal = { git = "https://github.com/gobftald/esp-hal.git", branch = "patches" }
#esp-metadata-generated = { git = "https://github.com/gobftald/esp-hal.git", branch = "patches" }
#esp-println = { git = "https://github.com/gobftald/esp-hal.git", branch = "patches" }
#esp-radio = { git = "https://github.com/gobftald/esp-hal.git", branch = "patches" }
#esp-rom-sys = { git = "https://github.com/gobftald/esp-hal.git", branch = "patches" }
#esp-rtos = { git = "https://github.com/gobftald/esp-hal.git", branch = "patches" }
#xtensa-lx = { git = "https://github.com/gobftald/esp-hal.git", branch = "patches" }

lcd-async = { git = "https://github.com/gobftald/lcd-async.git" }

rtos-trace = { git = "https://github.com/gobftald/rtos-trace.git" }
systemview-target = { git = "https://github.com/gobftald/rtos-trace.git" }

esp-alloc = { path = "../esp-hal/esp-alloc" }
esp-backtrace = { path = "../esp-hal/esp-backtrace" }
esp-bootloader-esp-idf = { path = "../esp-hal/esp-bootloader-esp-idf" }
esp-config = { path = "../esp-hal/esp-config" }
esp-hal = { path = "../esp-hal/esp-hal" }
esp-metadata-generated = { path = "../esp-hal/esp-metadata-generated" }
esp-println = { path = "../esp-hal/esp-println" }
esp-radio = { path = "../esp-hal/esp-radio" }
esp-rom-sys = { path = "../esp-hal/esp-rom-sys" }
esp-rtos = { path = "../esp-hal/esp-rtos" }
xtensa-lx = { path = "../esp-hal/xtensa-lx" }

#rtos-trace = { path = "../rtos-trace/rtos_trace" }
#systemview-target = { path = "../rtos-trace/systemview_target" }

[env]
# esp-hal defaults to "quad" but ESP32-S3-Touch-LCD-2 use "octal" PSRAM
ESP_HAL_CONFIG_PSRAM_MODE = "octal"

# Explicitly add _zicsr to the architecture string for C/C++ builds
# SEGGER/SEGGER_SYSVIEW.c needs it.
CFLAGS = "-march=rv32imc_zicsr"

AP_SSID = "CCM-GP450"
AP_GW_IP = "192.168.3.1"

AP_DHCP_SUBNET = "255.255.255.0"
AP_DHCP_POOL_START = "192.168.3.2"
AP_DHCP_POOL_END = "192.168.3.5"

HOME_SSID = "iWiFi-2.4"
HOME_PWD = "dingomolarsanta"
HOME_FIX_IP = "192.168.2.101"
HOME_ROUTER = "192.168.2.1"

TETH_SSID = "DK10"
TETH_PWD = "haho9024"

TFTP_PORT = "69"
ECU_PORT = "1990"
NMEA_PORT = "1992"
GSM_PORT = "1994"
