[package]
name = "esp-hal-procmacros"
version = "0.18.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.11"
proc-macro-crate  = "3.3.0"
proc-macro-error2 = "2.0.1"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.100", features = ["extra-traits", "full"] }
termcolor = "1.4"

[features]
## Provide a `#[main]` procmacro to mark the entry point for Embassy applications.
embassy = []
