.libpp : ALIGN(4)
{
    /* esf_buf.o */
         *(.text.esf_buf_alloc_dynamic_default_handler)
        *(.text.esf_buf_alloc_default_handler)
        *(.text.esf_buf_recycle_default_handler)
        *(.text.esf_buf_setup_static)
        *(.text.esf_buf_free_static)
        *(.text.esf_buf_setdown)
        *(.text.esf_buf_setup)

    /* if_hecfg.o */

    /* if_hwctrl.o */
        *(.text.ic_get_addr)
        *(.text.ic_get_ptk_alg)
        *(.text.ic_disable_crypto)
        *(.text.ic_set_key)
        *(.text.ic_get_key)
        *(.text.ic_obtain_key)
        *(.text.ic_tx_pkt)
        *(.text.ic_register_tx_cb)
        *(.text.ic_register_rx_cb)
        *(.text.ic_register_timer_post_cb)
        *(.text.ic_register_michael_mic_failure_cb)
        *(.text.ic_register_pp_tx_done_cb)
        *(.text.ic_register_config_cb)
        *(.text.ic_is_mgmt_hwdecr_enabled)
        *(.text.ic_register_pm_tx_null_cb)
        *(.text.ic_register_net80211_tx_cb)
        *(.text.ic_register_timer_cb)
        *(.text.ic_register_ftm_callbacks)
        *(.text.ic_enable_sniffer)
        *(.text.ic_disable_sniffer)
        *(.text.ic_set_vif)
        *(.text.ic_get_next_tbtt)
        *(.text.ic_del_rx_ba)
        *(.text.ic_add_rx_ba)
        *(.text.ic_reset_tbtt)
        *(.text.ic_del_key_all)
        *(.text.ic_del_key)
        *(.text.ic_set_ac_param)
        *(.text.ic_ampdu_op)
        *(.text.ic_set_trc)
        *(.text.ic_deinit)
        *(.text.ic_init)
        *(.text.ic_set_interrupt_handler)
        *(.text.ic_clear_interrupt_handler)
        *(.text.ic_enable_rx)
        *(.text.ic_disable_rx)
        *(.text.ic_set_beacon_int)
        *(.text.ic_set_mac)
        *(.text.ic_set_bssid)
        *(.text.ic_set_current_channel)
        *(.text.ic_get_random)
        *(.text.ic_get_pp_hdl)
        *(.text.ic_set_rx_policy_ubssid_check)
        *(.text.ic_set_rx_policy)
        *(.text.ic_set_sta_auth_flag)
        *(.text.ic_set_interface)
        *(.text.ic_trc_set_per_pkt_rate)
        *(.text.ic_trc_update_ifx_phy_mode)
        *(.text.ic_stop_hw_txq)
        *(.text.ic_stop_sw_txq)
        *(.text.ic_create_wifi_task)
        *(.text.ic_delete_wifi_task)
        *(.text.ic_update_sta_tsf)
        *(.text.ic_rx_enable_bssid_check)
        *(.text.ic_get_default_sched)

    /* lmac.o */
        *(.text.lmacGetTxFrame)
        *(.text.lmacSetAcParam)
        *(.text.lmacInitAc)
        *(.text.lmacInit)
        *(.text.lmacEndRetryAMPDUFail)
        *(.text.lmacDebugTxDrop)
        *(.text.lmac_record_txtime)
        *(.text.lmac_update_tx_statistic)
        *(.text.lmacDiscardMSDU)
        *(.text.lmacRetryTxFrame)
        *(.text.lmacProcessTxopQComplete)
        *(.text.lmacProcessShortRetryFail)
        *(.text.lmacProcessCtsTimeout)
        *(.text.lmacProcessLongRetryFail)
        *(.text.lmacProcessCollision)
        *(.text.lmacProcessCollisions_task)
        *(.text.lmacProcessAckTimeout)
        *(.text.lmacProcessTxRtsError)
        *(.text.lmacProcessTxseckiderr)
        *(.text.lmacProcessTxError)
        *(.text.lmacDisableTransmit)
        *(.text.lmacProcessTxTimeout)
        *(.text.lmacStopTransmit)
        *(.text.lmac_stop_hw_txq)

    /* pm.o */
        *(.text.hal_pm_unblock_txq)
        *(.text.hal_clear_sta_tsf_active_state)
        *(.text.pm_incr_active_cnt)
        *(.text.pm_incr_coex_active_cnt)
        *(.text.pm_disable_active_timer)
        *(.text.pm_update_at_next_beacon)
        *(.text.pm_beacon_monitor_tbtt_timeout)
        *(.text.pm_beacon_monitor_timeout)
        *(.text.pm_connectionless_wake_window_timeout)
        *(.text.pm_connectionless_wake_interval_timeout)
        *(.text.pm_disconnected_sleep_delay_timeout)
        *(.text.pm_coex_slice_wifi_timeout)
        *(.text.pm_sleep_delay_timeout)
        *(.text.pm_active_timeout)
        *(.text.pm_dream_timeout)
        *(.text.pm_is_sleeping)
        *(.text.pm_is_open)
        *(.text.pm_noise_check_disable)
        *(.text.pm_noise_check_enable)
        *(.text.pm_disable_disconnected_sleep_delay_timer)
        *(.text.pm_enable_disconnected_sleep_delay_timer)
        *(.text.pm_noise_check)
        *(.text.pm_pend_noise_check)
        *(.text.pm_noise_check_process)
        *(.text.pm_register_pm_tx_null_cb)
        *(.text.pm_send_nullfunc)
        *(.text.pm_disconnected_wake)
        *(.text.pm_disconnected_sleep)
        *(.text.pm_wake_up)
        *(.text.pm_send_probe_start)
        *(.text.pm_off_channel)
        *(.text.pm_wake_done)
        *(.text.pm_coex_separate_connectionless_window)
        *(.text.pm_go_to_sleep)
        *(.text.pm_set_next_tbtt)
        *(.text.pm_mesh_set_next_tbtt)
        *(.text.pm_beacon_timestamp_statistic)
        *(.text.pm_beacon_misc_process)
        *(.text.pm_coex_schm_process)
        *(.text.pm_coex_schm_process_restart)
        *(.text.pm_coex_slice_timeout_process)
        *(.text.pm_dream_timeout_process)
        *(.text.pm_sleep_delay_timeout_process)
        *(.text.pm_disconnected_sleep_delay_timeout_process)
        *(.text.pm_tx_data_done_process)
        *(.text.pm_tx_null_data_done_process)
        *(.text.pm_go_to_wake)
        *(.text.pm_send_probe_stop)
        *(.text.pm_on_channel)
        *(.text.pm_update_params)
        *(.text.pm_coex_tbtt_process)
        *(.text.pm_active_timeout_process)
        *(.text.pm_send_sleep_null_cb)
        *(.text.pm_send_wake_null_cb)
        *(.text.pm_on_coex_schm_process_restart)
        *(.text.pm_on_coex_schm_status_config)
        *(.text.pm_on_coex_start)
        *(.text.pm_on_probe_resp_rx)
        *(.text.pm_on_data_tx_done)
        *(.text.pm_disconnected_start)
        *(.text.pm_disconnected_stop)
        *(.text.pm_start)
        *(.text.pm_stop)
        *(.text.pm_attach)
        *(.text.pm_deattach)
        *(.text.pm_force_scan_unlock)
        *(.text.pm_enable_sta_disconnected_power_management)

    /* pm_coex.o */
        *(.text.pm_coex_reconnect_policy)
        *(.text.pm_coex_set_reconnect_policy)

    /* pm_extend.o */

    /* pm_mbssid.o */

    /* pm_twt.o */

    /* pp.o */
        *(.text.pp_delete_task_manually)
        *(.text.getle32)
        *(.text.putle32)
        *(.text.xswap)
        *(.text.pp_register_net80211_tx_cb)
        *(.text.pp_register_config_cb)
        *(.text.pp_register_timer_cb)
        *(.text.pp_register_michael_mic_failure_cb)
        *(.text.pp_default_event_handler)
        *(.text.ppRegisterTxDoneUserActionCallback)
        *(.text.ppRegisterRxCallback)
        *(.text.ppRegisterTxCallback)
        *(.text.ppCheckTxQIdle)
        *(.text.ppCheckIsConnTraffic)
        *(.text.ppCheckTxConnTrafficIdle)
        *(.text.ppSetInterface)
        *(.text.pp_gettid)
        *(.text.ppAssembleMicHdr)
        *(.text.ppCalTkipMic)
        *(.text.ppTxFragmentProc)
        *(.text.ppClearRxFragment)
        *(.text.ppFillAMPDUBar)
        *(.text.ppReSendBar)
        *(.text.pp_create_task)
        *(.text.pp_deattach)
        *(.text.ppInitTxq)
        *(.text.pp_delete_task)
        *(.text.ppCheckTxIdle)
        *(.text.ppCalTxopDur)
        *(.text.ppPrepareBarFrame)
        *(.text.pp_attach)
        *(.text.ppClearTxq)
        *(.text.pp_stop_sw_txq)
        *(.text.ppGetTaskHdl)

    /* pp_debug.o */
        *(.text.dbg_lmac_ps_statis_reset)
        *(.text.dbg_lmac_init)

    /* pp_he.o */

    /* pp_he_ctrl.o */

    /* pp_test.o */

    /* pp_timer.o */
        *(.text.pp_timer_beacon_monitor_tbtt)
        *(.text.pp_timer_beacon_monitor)
        *(.text.pp_timer_connectionless_wake_window)
        *(.text.pp_timer_connectionless_wake_interval)
        *(.text.pp_timer_disconnected_sleep_delay)
        *(.text.pp_timer_sleep_delay)
        *(.text.pp_timer_coex_slice)
        *(.text.pp_timer_active)
        *(.text.pp_timer_dream)
        *(.text.pp_timer_noise_check)
        *(.text.pp_timer_register_post_cb)
        *(.text.pp_timer_process)

    /* pp_vht.o */

    /* rate_control.o */
        *(.text.RC_GetDuration)
        *(.text.RC_SetBasicRate)
        *(.text.RC_GetCtsTime)

    /* trc.o */
        *(.text.rc11NRate2SchedIdx)
        *(.text.rc11GRate2SchedIdx)
        *(.text.rc11BRate2SchedIdx)
        *(.text.rcLoRaRate2SchedIdx)
        *(.text.rcBuildIndex)
        *(.text.rcUpdateAMPDUParam)
        *(.text.rcGet11NHighestRateIdx)
        *(.text.rcGet11GHighestRateIdx)
        *(.text.rcGet11BHighestRateIdx)
        *(.text.rcGetDefaultHigestRateIdx)
        *(.text.rcGetHighestRateIdx)
        *(.text.rcUpdatePhyMode)
        *(.text.rcTxUpdatePer)
        *(.text.trc_set_per_pkt_rate)
        *(.text.rc_get_default_sched)
        *(.text.rcUpdateRate)
        *(.text.rcReachRetryLimit)
        *(.text.rcAttach)
        *(.text.rc_disable_trc)
        *(.text.rc_disable_trc_by_interface)
        *(.text.trc_init)
        *(.text.trc_update_ifx_phy_mode)
        *(.text.trc_deinit)
        *(.text.rc_set_per_conn_fix_rate)
        *(.text.rc_enable_trc)

    /* wdev.o */
        *(.text.wdev_csi_hw_bug_check)
        *(.text.wDev_ftm_set_t1t4)
        *(.text.wdev_csi_rx_process)
        *(.text.wDev_SnifferRxData)
        *(.text.wDev_IndicateCtrlFrame)
        *(.text.wDev_SnifferRxAmpdu)
        *(.text.wDev_SetCurChannel)
        *(.text.wDev_SetAuthed)
        *(.text.wDev_Set_Beacon_Int)
        *(.text.wDev_Reset_TBTT)
        *(.text.wDev_reset_bcnSendTick)
        *(.text.wDev_Get_Next_TBTT)
        *(.text.wdev_set_promis_misc_pkt)
        *(.text.wdev_set_promis_ctrl_pkt)
        *(.text.wdev_set_promis)
        *(.text.wDev_ftm_record_t1t4)
        *(.text.wDev_ftm_record_t2t3)
        *(.text.wdev_ftm_set_callbacks)
        *(.text.wDev_record_ftm_data_local)
        *(.text.wDev_Rxbuf_Deinit)
        *(.text.wDev_Rxbuf_Init)
        *(.text.wDev_disable_low_rate)
        *(.text.wDev_enable_low_rate)
        *(.text.wDev_Insert_KeyEntry)
        *(.text.wDev_remove_KeyEntry)
        *(.text.wDev_remove_KeyEntry_all_cnx)
        *(.text.wDev_Crypto_Disable)
        *(.text.wdev_is_mgmt_hwdecr_enabled)
        *(.text.wdev_data_init)
        *(.text.wdev_funcs_init)
        *(.text.wdev_funcs_deinit)

    /* hal_ampdu.o */
        *(.text.hal_agreement_add_rx_ba)
        *(.text.hal_agreement_del_rx_ba)
        *(.text.hal_ba_session_restore_by_hw_index)

    /* hal_coex.o */
        *(.text.hal_coex_pti_init)
        *(.text.hal_set_rx_beacon_pti)
        *(.text.hal_set_rx_beacon_time)
        *(.text.hal_set_rx_active_pti)
        *(.text.hal_set_rx_ack_pti)
        *(.text.hal_set_wifi_default_pti)

    /* hal_crypto.o */
        *(.text.hal_crypto_clr_key_entry)
        *(.text.hal_crypto_set_key_entry)
        *(.text.hal_crypto_is_key_valid)
        *(.text.hal_crypto_get_key_entry)
        *(.text.hal_crypto_init)
        *(.text.hal_crypto_mgmt_rx_enabled)
        *(.text.hal_crypto_enable)
        *(.text.hal_crypto_disable)

    /* hal_he_common.o */

    /* hal_mac.o */
        *(.text.mac_tx_set_plcp0)
        *(.text.mac_tx_set_duration)
        *(.text.hal_mac_tx_set_ppdu)
        *(.text.hal_mac_set_txq_invalid)
        *(.text.hal_mac_is_txq_valid)
        *(.text.hal_mac_tx_set_cca)
        *(.text.hal_mac_disable_low_rate)
        *(.text.hal_mac_enable_low_rate)
        *(.text.mac_rxbuf_init)
        *(.text.mac_txrx_init)
        *(.text.hal_mac_set_rxq_policy)
        *(.text.mac_last_rxbuf_init)
        *(.text.hal_deinit)
        *(.text.hal_mac_set_addr)
        *(.text.hal_mac_set_bssid)
        *(.text.hal_mac_rx_set_policy)
        *(.text.hal_init)
        *(.text.hal_mac_tsf_reset)
        *(.text.hal_disable_sta_beacon_filter)
        *(.text.hal_rx_enable_bssid_check)
        *(.text.hal_mac_ftm_get_t3)

    /* hal_mac_rx.o */

    /* hal_mac_tx.o */
        *(.text.mac_tx_set_plcp1)
        *(.text.mac_tx_set_plcp2)
        *(.text.mac_tx_set_htsig)
        *(.text.hal_mac_fill_hwtxop)
        *(.text.mac_tx_set_txop_q)
        *(.text.hal_mac_get_txq_state)
        *(.text.hal_mac_clr_txq_state)
        *(.text.hal_mac_get_txq_pmd)
        *(.text.hal_attenna_init)
        *(.text.hal_mac_rate_autoack_init)

    /* hal_pwr.o */

    /* hal_sniffer.o */
        *(.text.hal_sniffer_enable)
        *(.text.hal_sniffer_disable)
        *(.text.hal_sniffer_rx_set_promis)
        *(.text.hal_sniffer_set_promis_misc_pkt)

    /* hal_tsf.o */
        *(.text.hal_enable_sta_tsf)
        *(.text.hal_disable_sta_tsf)
        *(.text.hal_disable_softap_tsf)
        *(.text.hal_timer_update_by_rtc)
        *(.text.hal_set_sta_tsf)
        *(.text.hal_enable_sta_tbtt)
        *(.text.hal_disable_sta_tbtt)
        *(.text.hal_set_sta_tbtt)
        *(.text.hal_set_sta_tbtt_interval)
        *(.text.hal_set_sta_tbtt_ahead_time)
        *(.text.hal_set_sta_tsf_wakeup)
        *(.text.hal_tsf_get_tbttstart)
        
} > ROTEXT