#![no_std]
#![allow(non_camel_case_types)]
/// Peripheral access API for ESP32-C3 microcontrollers (generated using svd2rust v0.35.0 ( ))
///
/// You can find an overview of the generated API [here].
///
/// API features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository],
/// checking out the above commit, and running `cargo doc --open`.
///
/// [here]: https://docs.rs/svd2rust/0.35.0/svd2rust/#peripheral-api
/// [next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased
/// [repository]: https://github.com/rust-embedded/svd2rust"]
// 6
use core::{marker::PhantomData, ops::Deref};

// 10
#[allow(unused_imports)]
use generic::*;
/// Common register and bit access and modify traits
pub mod generic;

/// System Timer
// 1453
pub struct SYSTIMER {
    _marker: PhantomData<*const ()>,
}
// unsafe impl Send for SYSTIMER {}
impl SYSTIMER {
    /// Pointer to the register block
    pub const PTR: *const systimer::RegisterBlock = 0x6002_3000 as *const _;
}
impl Deref for SYSTIMER {
    type Target = systimer::RegisterBlock;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        unsafe { &*Self::PTR }
    }
}
/// System Timer
pub mod systimer;
