[device]
name  = "esp32c3"
arch  = "riscv"
cores = "single_core"

peripherals = [
    # Peripherals available in the PAC:
    "interrupt_core0",
    "rng",
    "rtc_cntl",
    "system",
    "systimer",
    "timg0",
]

symbols = [
    # Executor parameters
    "low_power_wait",
    "integrated_timers",
    "single_queue",
    
    #[device.timergroup]
    "timergroup",

    ## Radio
    #[device.wifi]
    "wifi",
]

memory = []
