[device]
name  = "esp32c3"
arch  = "riscv"
cores = "single_core"

peripherals = [
    # Peripherals available in the PAC:
    "efuse",
    "interrupt_core0",
    "rng",
    "rtc_cntl",
    "system",
    "systimer",
    "timg0",
]

symbols = [
    # Additional peripherals defined by us (the developers):
    "phy",
    "wifi",

    # Executor parameters
    "low_power_wait",
    "integrated_timers",
    "single_queue",

    # phy configs
    "phy_enable_usb",                       # description: Keeps USB running when using WiFi.
                                            #              This allows debugging and log messages via USB Serial JTAG.
                                            #              Turn off for best WiFi performance.
                                            # default:     - value: true
    
    "phy_full_calibration",                 # description: Use PHY_RF_CAL_FULL instead of PHY_RF_CAL_PARTIAL.
                                            # default:     - value: true

    "phy_skip_calibration_after_deep_sleep" # description: Use PHY_RF_CAL_NONE after deep sleep.
                                            # default:     - value: true

]
 
memory = []
