[device]
name  = "esp32s2"
arch  = "xtensa"
cores = "single_core"

peripherals = [
    "interrupt_core0",
]

symbols = [
    # Additional peripherals defined by us (the developers):
    "large_intr_status",
]
