[device]
name  = "esp32c6"
arch  = "riscv"
cores = "single_core"

peripherals = [
    "interrupt_core0",
]

symbols = [
    # Additional peripherals defined by us (the developers):
    "large_intr_status",
    "plic",
]
