[device]
name  = "esp32s3"
arch  = "xtensa"
cores = "multi_core"

peripherals = [
    "interrupt_core0",
    "interrupt_core1",
]

symbols = [
    # Additional peripherals defined by us (the developers):
    "very_large_intr_status",
]
