[package]
name = "esp-wifi"
version = "0.14.0"
edition = "2024"

[dependencies]
console = { path = "../../console", features = ["usb_uart"]}
defmt = { version = "0.3.10", optional = true }
esp-hal = { path = "../esp-hal" }
rand_core = { path = "../../rand_core" }
cfg-if = "1.0.0"

[build-dependencies]
esp-metadata = { path = "../esp-metadata" }

[features]
# Target the ESP32-C3.
esp32c3 = [
  "esp-hal/esp32c3",
  #"esp-wifi-sys/esp32c3",
]

## Enable WiFi support
wifi = []
