[package]
name = "esp-backtrace"
version = "0.16.0"
edition = "2024"

[dependencies]
heapless = "0.8"
defmt    = { version = "0.3.10", optional = true }
console  = { path = "../../console", features = ["jtag_serial"] }      # default console

[features]
default = ["esp32c3"]

esp32c3 = []
defmt   = ["dep:defmt", "console/defmt"]

panic-handler     = []
exception-handler = []
