[package]
name = "esp-backtrace"
version = "0.16.0"
edition = "2024"

[dependencies]
#console  = { path = "../../console", features = ["jtag_serial"] }      # default console
#defmt    = { version = "0.3.10", optional = true }
defmt       = { version = "1", optional = true }
#esp-println = { version = "0.16.1", optional = true, default-features = false, path = "../esp-println" }
esp-println = { version = "0.16.1", optional = true, default-features = false }
esp-config  = { version = "0.4.0", path = "../esp-config" }
heapless = "0.8"

[features]
default = ["esp32c3"]

esp32c3 = []
#defmt   = ["dep:defmt", "console/defmt"]
#defmt   = ["dep:defmt"]

panic-handler     = []
exception-handler = []
