[package]
name = "console"
version = "0.1.0"
edition = "2024"

[dependencies]
defmt = { version = "0.3.10", optional = true }
critical-section = { version = "1.2.0", optional = true }
portable-atomic = { path = "../portable-atomic", default-features = false, optional = true }

[features]
# usb_uart and jtag_serial are mutual exclusive but one of them should be selected
usb_uart = []                       # if usb_uart is off we cannot use any printing mechanism
                                    # if usb_uart is on but defmt is off only core_println (usb_uart) prints
                                    # altough we can use println but it gives an empty block
jtag_serial = ["portable-atomic"]   # same HW as usb_uart but handling buffer overrun

defmt = [
                                    # needs runner = "espflash flash --monitor --log-format defmt"
                                    # needs "-C", "link-arg=-Tdefmt.x" rustflag in config.toml
    #"usb_uart",                    # needs usb_console
    "jtag_serial",                  # needs usb_console
    "dep:defmt",
    "critical-section"
]

critical-section = ["dep:critical-section"]