.libnet80211 : ALIGN(4)
{
    /* ieee80211_action.o */
        *(.text.send_inval)
        *(.text.recv_inval)
        *(.text.ieee80211_send_action_register)
        *(.text.ieee80211_send_action)
        *(.text.ieee80211_recv_action_register)
        *(.text.ieee80211_recv_action)

    /* ieee80211_action_vendor.o */
        *(.text.get_iav_key)
        *(.text.ieee80211_recv_action_vendor_spec)
        *(.text.ieee80211_action_vendor_spec_attach)
        *(.text.ieee80211_recv_action_vendor_esp_now)

    /* ieee80211_api.o */
        *(.text.wifi_ant_update_empty_func)
        *(.text.esp_wifi_set_inactive_time_local)
        *(.text.wifi_get_init_state)
        *(.text.wifi_is_stop_in_progress)
        *(.text.wifi_api_lock)
        *(.text.wifi_api_unlock)
        *(.text.wifi_init_completed)
        *(.text.wifi_softap_get_config)
        *(.text.esp_wifi_get_mode)
        *(.text.wifi_deinit_in_caller_task)
        *(.text.wifi_init_in_caller_task)
        *(.text.wifi_osi_funcs_register)
        *(.text.net80211_data_ptr_init)
        *(.text.net80211_softap_funcs_init)
        *(.text.net80211_funcs_init)
        *(.text.net80211_funcs_deinit)
        *(.text.esp_wifi_init_internal)
        *(.text.esp_wifi_set_mode)
        *(.text.esp_wifi_start)
        *(.text.esp_wifi_set_config)
        *(.text.esp_wifi_internal_reg_rxcb)
        *(.text.wifi_event_post)
        *(.text.wifi_mesh_event_post)
        *(.text.esp_wifi_vnd_lora_enable)
        *(.text.esp_wifi_vnd_lora_disable)
        *(.text.esp_wifi_get_event_mask)
        *(.text.esp_wifi_ipc_internal)
        *(.text.esp_wifi_internal_on_coex_start)
        *(.text.esp_wifi_internal_on_coex_schm_phase)
        *(.text.esp_wifi_set_tx_done_cb)
        *(.text.esp_wifi_set_inactive_time)
        *(.text.esp_mesh_get_running_active_duty_cycle)
        *(.text.esp_wifi_set_country)
        *(.text.esp_wifi_set_protocol)
        *(.text.esp_wifi_stop)
        *(.text.esp_wifi_deinit_internal)
        *(.text.esp_wifi_set_ps)

    /* ieee80211_btwt.o */

    /* ieee80211.o */
        *(.text.ieee80211_freedom_inside_cb)
        *(.text.ieee80211_send_sa_query)
        *(.text.ieee80211_send_sa_query_resp)
        *(.text.ieee80211_send_sa_query_req)
        *(.text.ieee80211_recv_sa_query_resp)
        *(.text.ieee80211_recv_sa_query_req)
        *(.text.ieee80211_rate_ref_init)
        *(.text.ieee80211_freedom_init)
        *(.text.ieee80211_user_ie_init)
        *(.text.ieee80211_ifattach)
        *(.text.ieee80211_ifdetach)
        *(.text.wifi_destroy_softap)
        *(.text.wifi_destroy_sta)
        *(.text.ieee80211_find_elem_match)
        *(.text.ieee80211_find_ie)
        *(.text.ieee80211_setup_pmf)
        *(.text.wifi_create_softap)
        *(.text.wifi_create_sta)
        *(.text.wifi_mode_set)
        *(.text.band2str)
        *(.text.ieee80211_get_tx_info_from_eb)
        *(.text.ieee80211_freedom_deinit)
        *(.text.ieee80211_find_elem)

    /* ieee80211_crypto.o */        
        *(.text.ieee80211_crypto_attach)
        *(.text.ieee80211_crypto_decap)
        *(.text.ieee80211_crypto_aes_128_cmac_decrypt)
        *(.text.ieee80211_crypto_gmac_decrypt)
        *(.text.ieee80211_get_cipher_mic_len)
        *(.text.ieee80211_crypto_bip_encrypt)

    /* ieee80211_crypto_ccmp.o */
        *(.text.ccmp_encap)
        *(.text.ccmp_decap)
        *(.text.ieee80211_decrypt_espnow_pkt)
        *(.text.ieee80211_ccmp_decrypt)

    /* ieee80211_crypto_gcmp.o */
        *(.text.gcmp_encap)
        *(.text.gcmp_decap)

    /* ieee80211_crypto_sms4.o */
        *(.text.sms4_decap)
        *(.text.sms4_encap)

    /* ieee80211_crypto_tkip.o */
        *(.text.tkip_decap)
        *(.text.tkip_encap)

    /* ieee80211_crypto_wep.o */
        *(.text.wep_encap)
        *(.text.wep_decap)

    /* ieee80211_debug.o */
        *(.text.wifi_log)

    /* ieee80211_ets.o */
        *(.text.ieee80211_getmgtframe)
        *(.text.ieee80211_getbcnframe)

    /* ieee80211_ftm.o */
        *(.text.ftm_get_phy_comp)
        *(.text.ieee80211_ftm_measurement_txcb)
        *(.text.ftm_session_timeout)
        *(.text.ftm_send_msmt_pkt)
        *(.text.ftm_request_timeout)
        *(.text.ftm_send_request)
        *(.text.ftm_record_t2t3_cb)
        *(.text.ftm_offchan_end)
        *(.text.public_send_action_ftm_req)
        *(.text.ftm_is_responder_supported)
        *(.text.ftm_get_resp_session_for_peer)
        *(.text.ftm_get_resp_session_by_cookie)
        *(.text.ftm_add_resp_session)
        *(.text.ftm_free_resp_session)
        *(.text.ftm_record_t1t4_cb)
        *(.text.ftm_set_t1t4_cb)
        *(.text.ftm_responder_cleanup)
        *(.text.ftm_resp_get_burst_slot)
        *(.text.ftm_resp_get_burst_inst_delay)
        *(.text.public_send_action_ftm_resp)
        *(.text.ieee80211_ftm_sess_timeout_process)
        *(.text.ieee80211_tx_ftm_msmt_process)
        *(.text.ftm_resp_allocate_para)
        *(.text.ftm_create_responder_session)
        *(.text.ftm_send_initial_resp)
        *(.text.public_recv_action_ftm_req)
        *(.text.ftm_is_initiator_supported)
        *(.text.ftm_initiator_post_event)
        *(.text.ftm_parse_data)
        *(.text.ftm_initiator_session_end)
        *(.text.ftm_initiator_session_abort)
        *(.text.ieee80211_ftm_request_txcb)
        *(.text.ieee80211_send_ftmr_process)
        *(.text.ftm_initiator_process_resp)
        *(.text.public_recv_action_ftm_resp)
        *(.text.ftm_initiator_negotiate_session)
        *(.text.ftm_offchan_tx_req)
        *(.text.ftm_initiator_start_session)
        *(.text.ieee80211_ftm_req_timeout_process)
        *(.text.ftm_initiator_cleanup)
        *(.text.ieee80211_ftm_attach)
        *(.text.ieee80211_ftm_detach)

    /* ieee80211_he.o */

    /* ieee80211_hostap.o */
        *(.text.is_non_esp_oui)
        *(.text.is_esp_manufacturer_oui)
        *(.text.ieee80211_is_action_category_robust)
        *(.text.ieee80211_hostapd_beacon_txcb)
        *(.text.ieee80211_hostap_send_beacon)
        *(.text.hostap_handle_timer)
        *(.text.ap_try_sa_query)
        *(.text.ap_sa_query_timeout)
        *(.text.ieee80211_hostapd_ps_txcb)
        *(.text.ieee80211_free_beacon_eb)
        *(.text.ieee80211_hostap_send_beacon_process)
        *(.text.hostap_delete_ptk)
        *(.text.ieee80211_hostap_attach)
        *(.text.hostap_deliver_data)
        *(.text.hostap_handle_timer_process)
        *(.text.wifi_ap_reg_rxcb)
        *(.text.ap_rx_cb)
        *(.text.hostap_auth_open)
        *(.text.hostap_recv_ctl)
        *(.text.wifi_softap_start)
        *(.text.wifi_softap_stop)
        *(.text.ap_sa_query_timeout_process)
        *(.text.ap_try_sa_query_process)
        *(.text.hostap_recv_mgmt)
        *(.text.hostap_input)
        *(.text.add_mic_ie_bip)
        *(.text.free_mac_info)
        *(.text.clear_mac_queue)
        *(.text.hostap_add_in_mac_list)
        *(.text.hostap_query_mac_in_list)
        *(.text.hostap_del_mac_info_from_list)
        *(.text.create_new_bss_for_sa_query_failed_sta)

    /* ieee80211_ht.o */
        *(.text.addba_stop_timeout)
        *(.text.ieee80211_ampdu_timeout)
        *(.text.addba_timeout)
        *(.text.ieee80211_add_htcap_body)
        *(.text.ht_recv_action_ba_addba_response)
        *(.text.ampdu_tx_stop)
        *(.text.addba_response_txcb)
        *(.text.ieee80211_ht_attach)
        *(.text.ampdu_free_rx_ba_index)
        *(.text.ht_recv_action_ba_delba)
        *(.text.ampdu_alloc_rx_ba_index)
        *(.text.ht_recv_action_ba_addba_request)
        *(.text.ieee80211_ht_deattach)
        *(.text.ieee80211_ampdu_enable)
        *(.text.addba_timeout_process)
        *(.text.ieee80211_ampdu_request)
        *(.text.ieee80211_ampdu_age_all)
        *(.text.ampdu_process_multicast_address_qos_frame)
        *(.text.ieee80211_recv_bar)
        *(.text.ieee80211_ht_node_cleanup)
        *(.text.ieee80211_ht_node_init)
        *(.text.ieee80211_parse_htcap)
        *(.text.ieee80211_has_ht40_bss)
        *(.text.ieee80211_update_channel)
        *(.text.ieee80211_ht_updatehtcap)
        *(.text.ieee80211_ht_updateparams)
        *(.text.ieee80211_setup_htrates)
        *(.text.ieee80211_setup_basic_htrates)
        *(.text.ieee80211_add_htcap)
        *(.text.ieee80211_add_htcap_vendor)
        *(.text.ieee80211_add_htinfo_body)
        *(.text.ieee80211_add_htinfo)
        *(.text.ieee80211_add_htinfo_vendor)
        *(.text.ht_action_output)
        *(.text.ht_send_action_ba_delba)
        *(.text.ht_send_action_ba_addba)
        *(.text.ieee80211_decap1)
        *(.text.ieee80211_decap_amsdu)
        *(.text.public_recv_action_ht2040_coex)
        *(.text.addba_get_rap_from_private)
        *(.text.ieee80211_ampdu_stop_age_timer.part.0)
        *(.text.ampdu_rx_stop.constprop.0)
        *(.text.ampdu_rx_start.constprop.0)
        *(.text.ieee80211_ampdu_age_bss.isra.0)
        *(.text.ieee80211_process_bar_info)
        *(.text.hostap_ht_operation_update)

    /* ieee80211_ie_vendor.o */            
        *(.text.ieee80211_add_ie_vendor_esp_head)
        *(.text.ieee80211_add_ie_vendor_esp_manufacturer)

    /* ieee80211_input.o */
        *(.text.wpa_cipher)
        *(.text.rsn_cipher)
        *(.text.ieee80211_decap)
        *(.text.ieee80211_is_support_rate)
        *(.text.ieee80211_setup_rates)
        *(.text.ieee80211_set_max_rate)
        *(.text.ieee80211_is_lr_only)
        *(.text.ieee80211_setup_phy_mode)
        *(.text.ieee80211_setup_lr_rates)
        *(.text.ieee80211_alloc_challenge)
        *(.text.ieee80211_parse_beacon)
        *(.text.ieee80211_parse_wpa)
        *(.text.ieee80211_rsn_cipher_priority)
        *(.text.ieee80211_better_rsn_pairwise_cipher)
        *(.text.ieee80211_amsdu_negotiate)
        *(.text.ieee80211_parse_rsn)
        *(.text.ieee80211_is_ht_cipher)
        *(.text.ieee80211_parse_wapi)
        *(.text.ieee80211_parse_action)
        *(.text.ieee80211_setup_rateset)

    /* ieee80211_ioctl.o */
        *(.text.wifi_pmk_is_valid)
        *(.text.ieee80211_ioctl_process)
        *(.text.current_task_is_wifi_task)
        *(.text.adc2_wifi_acquire)
        *(.text.wifi_station_get_reconnect_policy)
        *(.text._do_wifi_stop)
        *(.text._do_wifi_start)
        *(.text.ieee80211_set_phy_bw)
        *(.text.wifi_station_save_ap_channel)
        *(.text.ieee80211_sta_disconnect)
        *(.text._do_wifi_disconnect)
        *(.text.wifi_softap_max_support_num)
        *(.text.wifi_softap_set_config)
        *(.text.chip_enable)
        *(.text.chip_disable)
        *(.text.wifi_reset_mac)
        *(.text.wifi_hw_start)
        *(.text.wifi_stop_sw_txq)
        *(.text.wifi_hw_stop)
        *(.text.wifi_set_mode_process)
        *(.text.wifi_menuconfig_init)
        *(.text.wpa_crypto_funcs_init)
        *(.text.wifi_crypto_init)
        *(.text.wifi_hmac_init)
        *(.text.wifi_lmac_init)
        *(.text.wifi_deinit)
        *(.text.wifi_init_process)
        *(.text.wifi_start_process)
        *(.text.wifi_disconnect_process)
        *(.text.wifi_set_config_process)
        *(.text.wifi_set_rxcb_process)
        *(.text.wifi_wps_is_started)
        *(.text.wifi_wpa2_is_started)
        *(.text.wifi_ipc_process)
        *(.text.ieee80211_set_appie)
        *(.text.wifi_set_appie_process)
        *(.text.wifi_register_mgmt_frame)
        *(.text.wifi_on_coex_start_process)
        *(.text.wifi_on_coex_schm_phase_process)
        *(.text.wifi_mesh_map_deauth_progress)
        *(.text.ieee80211_ioctl_init)
        *(.text.ieee80211_ioctl_deinit)
        *(.text.ieee80211_ioctl)
        *(.text.config_get_wifi_task_stack_size)
        *(.text.ieee80211_vnd_ie_size.part.0)
        *(.text.wifi_check_home_channel)
        *(.text.wifi_set_protocol_process)
        *(.text.ieee80211_set_phy_mode)
        *(.text.wifi_stop_process)
        *(.text.adc2_wifi_release)
        *(.text.wifi_stop_old_mode)
        *(.text.ieee80211_protocol_attach)
        *(.text.wifi_station_set_config_local_2.constprop.0)
        *(.text.wifi_txq_empty)
        *(.text.wifi_hw_mode_switch)
        *(.text.wifi_set_ps_process)
        *(.text.wifi_mesh_ps_duty_cycle_get_process)
        *(.text.wifi_set_country)
        *(.text.wifi_deinit_process)

    /* ieee80211_mbssid.o */

    /* ieee80211_mesh_quick.o */
        *(.text.is_esp_mesh_assoc)

    /* ieee80211_nan_common.o */

    /* ieee80211_nan_datapath.o */

    /* ieee80211_nan_disc.o */

    /* ieee80211_nan_sd.o */

    /* ieee80211_node.o */

    /* ieee80211_nvs.o */            
        *(.text.wifi_nvs_cfg_item_init)
        *(.text.wifi_nvs_cfg_init)
        *(.text.wifi_nvs_get)
        *(.text.wifi_nvs_commit)
        *(.text.wifi_nvs_set)
        *(.text.ieee80211_adjust_2nd_chan)
        *(.text.wifi_nvs_compare_cfg_diff)
        *(.text.wifi_set_default_ssid)
        *(.text.wifi_nvs_validate_ap_ssid)
        *(.text.wifi_nvs_validate_ap_password)
        *(.text.wifi_nvs_validate_sta_password)
        *(.text.wifi_nvs_validate_country)
        *(.text.wifi_nvs_validate_ap_chan)
        *(.text.wifi_nvs_validate_ap_num)
        *(.text.wifi_nvs_validate_sta_listen_interval)
        *(.text.wifi_nvs_load)
        *(.text.wifi_nvs_get_sta_listen_interval)
        *(.text.wifi_nvs_reset_current_ap_info)
        *(.text.wifi_nvs_deinit)
        *(.text.wifi_nvs_init)
        *(.text.wifi_nvs_validate_lr_info)

    /* ieee80211_output.o */
        *(.text.add_appie)
        *(.text.ieee80211_set_hmac_stop)
        *(.text.ieee80211_empty_txq)
        *(.text.is_wapi_alloc_tx_buf)
        *(.text.ieee80211_wapi_alloc_tx_buf)
        *(.text.ieee80211_amsdu_adjust_head)
        *(.text.ieee80211_amsdu_length_check)
        *(.text.ieee80211_output_init)
        *(.text.ieee80211_send_setup)
        *(.text.ieee80211_tx_mgt_cb)
        *(.text.ieee80211_classify)
        *(.text.ieee80211_add_rates)
        *(.text.ieee80211_add_dsparams)
        *(.text.ieee80211_add_xrates)
        *(.text.ieee80211_add_probe_resp_app_ies)
        *(.text.ieee80211_add_beacon_app_ies)
        *(.text.ieee80211_add_assoc_resp_ies)
        *(.text.ieee80211_add_assoc_req_ies)
        *(.text.ieee80211_add_probe_req_ies)
        *(.text.ieee80211_add_wme_param)
        *(.text.ieee80211_add_csa)
        *(.text.ieee80211_add_extcap)
        *(.text.ieee80211_vnd_ie_set)
        *(.text.ieee80211_vnd_lora_ie_size)
        *(.text.ieee80211_vnd_lora_ie_set)
        *(.text.ieee80211_setup_robust_mgmtframe)
        *(.text.ieee80211_mgmt_output)
        *(.text.ieee80211_getcapinfo)
        *(.text.ieee80211_assoc_req_construct)
        *(.text.ieee80211_assoc_resp_construct)
        *(.text.ieee80211_auth_construct)
        *(.text.ieee80211_get_robustmgtframe)
        *(.text.ieee80211_deauth_construct)
        *(.text.ieee80211_disassoc_construct)
        *(.text.ieee80211_output)
        *(.text.ieee80211_amsdu_send_check)
        *(.text.ieee80211_amsdu_encap_check)
        *(.text.ieee80211_encap_amsdu)
        *(.text.ieee80211_alloc_proberesp)
        *(.text.ieee80211_alloc_deauth)
        *(.text.ieee80211_output_raw_process)
        *(.text.ieee80211_beacon_construct)
        *(.text.ieee80211_send_nulldata)
        *(.text.ieee80211_send_probereq)
        *(.text.ieee80211_send_mgmt)
        *(.text.ieee80211_send_proberesp)
        *(.text.ieee80211_send_deauth_no_bss)
        *(.text.ieee80211_beacon_alloc)
        *(.text.ieee80211_encap_null_data)
        *(.text.ieee80211_pm_tx_null_process)
        *(.text.ieee80211_add_tie_param)
        *(.text.ieee80211_add_dh_param)
        *(.text.ieee80211_add_supportedchannels)
        *(.text.ieee80211_add_bss_max_idle)
        *(.text.ieee80211_encap_keep_alive_data)

    /* ieee80211_phy.o */
        *(.text.ieee80211_phy_deinit)
        *(.text.ieee80211_phy_type_get)
        *(.text.ieee80211_phy_mode_show)
        *(.text.ieee80211_setup_ratetable)
        *(.text.ieee80211_phy_init)

    /* ieee80211_power.o */
        *(.text.ieee80211_psq_init)
        *(.text.ieee80211_gpsq_init)
        *(.text.ieee80211_psq_find_max_bss)
        *(.text.ieee80211_set_tim)
        *(.text.ieee80211_psq_take_head)
        *(.text.ieee80211_psq_drop_one_pkt)
        *(.text.ieee80211_psq_send_one_pkt)
        *(.text.ieee80211_psq_is_buff_pkt)
        *(.text.ieee80211_pwrsave)
        *(.text.pwrsave_flushq)
        *(.text.ieee80211_node_pwrsave)
        *(.text.ieee80211_pwrsave_node_cleanup)
        *(.text.ieee80211_pwrsave_txcb)
        *(.text.ieee80211_is_bufferable_mmpdu)

    /* ieee80211_proto.o */    
        *(.text.ieee80211_proto_attach)
        *(.text.ieee80211_set_shortslottime)
        *(.text.ieee80211_wme_updateparams)
        *(.text.ieee80211_mlme_connect_bss)

    /* ieee80211_reg_db.o */
        *(.text.ieee80211_is_40mhz_valid_bw)

    /* ieee80211_regdomain.o */
        *(.text.ieee80211_regdomain_get_country)
        *(.text.ieee80211_update_phy_country)
        *(.text.ieee80211_regdomain_update)
        *(.text.ieee80211_regdomain_update_in_scan)
        *(.text.ieee80211_regdomain_update_in_connect)
        *(.text.ieee80211_add_countryie)
        *(.text.ieee80211_regdomain_max_chan)
        *(.text.ieee80211_regdomain_ap_max_chan)
        *(.text.ieee80211_regdomain_min_chan)
        *(.text.ieee80211_regdomain_ap_min_chan)
        *(.text.ieee80211_regdomain_chan_in_range)
        *(.text.ieee80211_regdomain_is_active_scan)
        *(.text.ieee80211_regdomain_check_ap_channel)
        *(.text.ieee80211_get_regdomain)
        *(.text.get_channel_max_bandwidth)
        *(.text.ieee80211_regdomain_check_channel)
        *(.text.ieee80211_regdomain_get_country_info)

    /* ieee80211_rfid.o */            
        *(.text.ieee80211_rfid_locp_recv_reset)
        *(.text.ieee80211_rfid_locp_recv)

    /* ieee80211_scan_5g.o */

    /* ieee80211_scan.o */
        *(.text.scan_enter_oper_channel)
        *(.text.scan_inter_channel_timeout)
        *(.text.scan_op_start)
        *(.text.ieee80211_scan_deattach)
        *(.text.scan_reset_default_app_params)
        *(.text.ieee80211_scan_attach)
        *(.text.scan_flush_all_tx_buf)
        *(.text.scan_cancel)
        *(.text.scan_remove_bssid)
        *(.text.scan_hidden_ssid)
        *(.text.scan_set_act_duration)
        *(.text.scan_set_pas_duration)
        *(.text.scan_add_probe_ssid)
        *(.text.scan_remove_probe_ssid)
        *(.text.scan_prefer_chan)
        *(.text.scan_update_scan_history)
        *(.text.scan_build_chan_list)
        *(.text.scan_set_desChan)
        *(.text.scan_get_type)
        *(.text.scan_check_hidden)
        *(.text.scan_reset_cipher_and_akm)
        *(.text.scan_profile_check)
        *(.text.free_bss_info)
        *(.text.clear_bss_queue)
        *(.text.scan_done)
        *(.text.scan_next_channel)
        *(.text.scan_enter_oper_channel_process)
        *(.text.scan_inter_channel_timeout_process)
        *(.text.scan_op_end)
        *(.text.scan_start)
        *(.text.check_bss_queue)
        *(.text.scan_parse_ht2040_coex)
        *(.text.scan_fill_wps_scan_ie)
        *(.text.scan_get_owe_channel_info)
        *(.text.scan_validate_owe_scenarios)
        *(.text.scan_parse_beacon)
        *(.text.scan_start_handler)
        *(.text.sta_update_owe_bssid.constprop.0)
        *(.text.scan_set_global_scan_times.constprop.0)
        *(.text.scan_pm_offchan)
        *(.text.scan_add_ssid_do.constprop.0)
        *(.text.scan_add_ssid.isra.0)
        *(.text.scan_enter_oper_channel_handler)

    /* ieee80211_sta.o */
        *(.text.sta_assoc_comeback)
        *(.text.sta_try_sa_query)
        *(.text.sta_sa_query_timeout)
        *(.text.wifi_sta_reg_rxcb)
        *(.text.ieee80211_wme_standard_ac_to_esp_ac)
        *(.text.sta_michael_mic_failure)
        *(.text.ieee80211_parse_wmeparams)
        *(.text.sta_rx_csa)
        *(.text.reset_cs_thres)
        *(.text.ieee80211_parse_obss_scan_param)
        *(.text.sta_recv_ctl)
        *(.text.wifi_station_start)
        *(.text.wifi_station_stop)
        *(.text.sta_bip_check)
        *(.text.sta_is_wpa3_enabled)
        *(.text.sta_is_11r_enabled)
        *(.text.sta_is_wifi_ent_enabled)
        *(.text.sta_get_owe_data)
        *(.text.sta_update_power_off_reset_flag)
        *(.text.ieee80211_sta_new_state)
        *(.text.sta_auth_ft)
        *(.text.sta_auth_open)
        *(.text.sta_auth_shared)
        *(.text.sta_auth_sae)
        *(.text.sta_retry_assoc)
        *(.text.sta_recv_assoc)
        *(.text.sta_sa_query_process_timeout)
        *(.text.sta_try_sa_query_process)
        *(.text.sta_recv_mgmt)
        *(.text.send_wake_null_timeout)
        *(.text.send_wake_null_timeout_process)
        *(.text.update_cs_thres)
        *(.text.ieee80211_set_bss_max_idle_period)
        *(.text.sta_is_bss_max_idle_enabled)

    /* ieee80211_supplicant.o */
        *(.text.wifi_sta_get_prof_password)
        *(.text.esp_wifi_sta_prof_is_wpa_internal)
        *(.text.ieee80211_set_key)
        *(.text.ieee80211_set_sta_gtk_index)
        *(.text.ieee80211_get_spp)
        *(.text.esp_wifi_unregister_wpa_cb_internal)
        *(.text.ieee80211_sta_is_connected)
        *(.text.wifi_set_rx_policy)
        *(.text.wifi_init_key)
        *(.text.ppInstallKey)
        *(.text.esp_wifi_set_appie_internal)
        *(.text.esp_wifi_unset_appie_internal)
        *(.text.ieee80211w_get_active_igtk_key_id)
        *(.text.ieee80211w_get_igtk_from_keyidx)
        *(.text.esp_wifi_register_mgmt_frame_internal)

    /* ieee80211_timer.o */
        *(.text.ieee80211_ampdu_age_handle)
        *(.text.ieee80211_addba)
        *(.text.ieee80211_ftm_sess_timeout)
        *(.text.ieee80211_ftm_req_timeout)
        *(.text.ieee80211_tx_ftm_msmt)
        *(.text.ieee80211_send_ftmr)
        *(.text.ieee80211_ap_try_sa_query)
        *(.text.ieee80211_ap_sa_query_timeout)
        *(.text.ieee80211_sta_retry_assoc)
        *(.text.ieee80211_sta_sa_query_timeout)
        *(.text.ieee80211_sta_try_sa_query)
        *(.text.ieee80211_assoc)
        *(.text.ieee80211_auth)
        *(.text.ieee80211_chm_dwell)
        *(.text.ieee80211_handshake)
        *(.text.ieee80211_beacon)
        *(.text.ieee80211_probe_send)
        *(.text.ieee80211_csa)
        *(.text.ieee80211_scan_enter_op_chan)
        *(.text.ieee80211_scan_inter_chan)
        *(.text.ieee80211_timer_connect)
        *(.text.ieee80211_hostap_handle)
        *(.text.ieee80211_send_beacon)
        *(.text.ieee80211_register_ftm_timer)
        *(.text.ieee80211_register_hostap_timer)
        *(.text.ieee80211_timer_do_process)
        *(.text.ieee80211_timer_process)
        *(.text.ieee80211_send_wake_null)           /* orphan */
        *(.text.ieee80211_cnx_connect_next_ap)      /* orphan */

    /* ieee80211_twt.o */

    /* ieee80211_vht.o */

    /* if_eagle.o */

    /* wl_chm.o */
        *(.text.chm_end_op_timeout)
        *(.text.chm_mhz2num)
        *(.text.chm_deinit)
        *(.text.chm_release_lock)
        *(.text.chm_end_op)
        *(.text.chm_end_op_timeout_process)
        *(.text.chm_cancel_op)
        *(.text.chm_acquire_lock)
        *(.text.chm_get_current_channel)
        *(.text.chm_get_home_channel)
        *(.text.chm_set_home_channel)
        *(.text.chm_get_chan_info)
        *(.text.chm_set_current_channel)
        *(.text.chm_init)
        *(.text.chm_change_channel)
        *(.text.chm_start_op)
        *(.text.chm_return_home_channel)
        *(.text.chm_phy_change_channel.constprop.0)
        *(.text.chm_check_channel_is_valid)
        *(.text.chm_get_snd_chan_mode)
        *(.text.chm_set_snd_chan)
        *(.text.chm_get_current_band)
        *(.text.chm_get_band_from_chan)
        *(.text.chm_get_channel_index)

    /* wl_cnx.o */
        *(.text.cnx_sta_connect_led_timer_cb)
        *(.text.cnx_cal_rc_util)
        *(.text.cnx_get_next_rc)
        *(.text.cnx_traverse_rc_lis_done)
        *(.text.cnx_connect_timeout)
        *(.text.cnx_handshake_timeout)
        *(.text.cnx_csa_fn)
        *(.text.mgd_probe_send_timeout)
        *(.text.cnx_beacon_timeout)
        *(.text.cnx_connect_op)
        *(.text.cnx_connect_to_bss)
        *(.text.cnx_probe_rc)
        *(.text.ieee80211_cnx_attach)
        *(.text._cnx_start_connect_without_scan)
        *(.text.cnx_can_do_obss_scan)
        *(.text.cnx_obss_scan)
        *(.text.cnx_obss_scan_timeout)
        *(.text.cnx_auth_timeout)
        *(.text.cnx_assoc_timeout)
        *(.text.wl_is_ap_no_lr)
        *(.text.wl_clear_ap_no_lr)
        *(.text.cnx_csa_fn_process)
        *(.text.cnx_validate_owe_bss)
        *(.text.cnx_bss_init)
        *(.text.cnx_get_authtype_strength)
        *(.text.cnx_check_bssid_in_blacklist)
        *(.text.cnx_remove_from_blacklist)
        *(.text.cnx_add_to_blacklist)
        *(.text.cnx_clear_blacklist)
        *(.text.cnx_choose_rc)
        *(.text.cnx_rc_search)
        *(.text.cnx_add_rc)
        *(.text.cnx_remove_all_rc)
        *(.text.cnx_do_handoff)
        *(.text.cnx_connect_next_ap)
        *(.text.cnx_start_handoff_cb)
        *(.text.cnx_remove_rc)
        *(.text.cnx_sta_connect_cmd)
        *(.text.cnx_connect_timeout_process)
        *(.text.cnx_auth_timeout_process)
        *(.text.cnx_assoc_timeout_process)
        *(.text.cnx_handshake_timeout_process)
        *(.text.cnx_bss_alloc)
        *(.text.cnx_remove_rc_except)
        *(.text.cnx_rc_update_rssi)
        *(.text.cnx_rc_update_state_metric)
        *(.text.cnx_probe_rc_tx_cb)
        *(.text.cnx_rc_update_age)
        *(.text.cnx_update_bss)
        *(.text.cnx_update_bss_more)
        *(.text.send_ap_probe)
        *(.text.cnx_beacon_timeout_process)
        *(.text.mgd_probe_send_timeout_process)
        *(.text.cnx_node_alloc)
        *(.text.cnx_node_remove)
        *(.text.cnx_is_any_node_connecting)
        *(.text.cnx_sta_pm)
        *(.text.ic_set_sta)
        *(.text.cnx_sta_leave)
        *(.text.cnx_sta_associated)
        *(.text.cnx_node_leave)
        *(.text.cnx_node_join)
        *(.text.cnx_start_obss_scan)
        *(.text.cnx_obss_scan_done_cb)
        *(.text.cnx_auth_done)
        *(.text.cnx_connect_next_ap_timeout)
        *(.text.update_ic_params_using_bss.part.0)
        *(.text.cnx_sta_pm.part.0)
        *(.text.cnx_connect_next_ap_timeout_process)

    /* wl_offchan.o */
        *(.text.offchan_in_progress)
        *(.text.offchan_recv_action)
        *(.text.offchan_send_action_tx_status)

    /* test.o */

    /* test_rx_bfee.o */

    /* test_rx_htc.o */

    /* test_rx_sniffer.o */

    /* test_rx_trig.o */

    /* test_tx_mbssid.o */
    
} > ROTEXT
