.esp-radio : ALIGN(4)
{
    /* esp-wifi-sys crate (dont't make a standalone script onnly for one function) */
    *(.text.coexist_printf)

    /* esp-radio continue/start */

    *(.text.*esp_radio*common_adapter*queue_recv*)
    *(.text.*esp_radio*common_adapter*queue_send*)
    *(.text.*esp_radio*common_adapter*queue_create*)
    *(.text.*esp_radio*common_adapter*queue_delete*)
    *(.text.*esp_radio*common_adapter*ets_timer_arm*)
    *(.text.*esp_radio*common_adapter*semphr_create*)
    *(.text.*esp_radio*common_adapter*semphr_delete*)
    *(.text.*esp_radio*common_adapter*ets_timer_done*)
    *(.text.*esp_radio*common_adapter*ets_timer_setfn*)
    *(.text.*esp_radio*common_adapter*ets_timer_disarm*)
    *(.text.*esp_radio*common_adapter*queue_msg_waiting*)
    *(.text.*esp_radio*common_adapter*read_mac*)

    *(.text.*esp_radio*compat*semaphore*sem_delete*)

    *(.text.*esp_radio*compat*timer_compat*compat_timer_arm_us*)

    *(.text.*esp_radio*compat*queue*queue_send_to_back*)
    *(.text.*esp_radio*compat*queue*queue_delete*)

    *(.text.*esp_radio*wifi*os_adapter*event_post*)
    *(.text.*esp_radio*wifi*os_adapter*get_random*)
    *(.text.*esp_radio*wifi*os_adapter*mutex_lock*)
    *(.text.*esp_radio*wifi*os_adapter*nvs_commit*)
    *(.text.*esp_radio*wifi*os_adapter*nvs_get_i8*)
    *(.text.*esp_radio*wifi*os_adapter*nvs_set_i8*)
    *(.text.*esp_radio*wifi*os_adapter*nvs_set_u8*)
    *(.text.*esp_radio*wifi*os_adapter*phy_enable*)
    *(.text.*esp_radio*wifi*os_adapter*task_delay*)
    *(.text.*esp_radio*wifi*os_adapter*nvs_set_u16*)
    *(.text.*esp_radio*wifi*os_adapter*phy_disable*)
    *(.text.*esp_radio*wifi*os_adapter*task_create*)
    *(.text.*esp_radio*wifi*os_adapter*task_delete*)
    *(.text.*esp_radio*wifi*os_adapter*wifi_calloc*)
    *(.text.*esp_radio*wifi*os_adapter*wifi_zalloc*)
    *(.text.*esp_radio*wifi*os_adapter*mutex_create*)
    *(.text.*esp_radio*wifi*os_adapter*mutex_delete*)
    *(.text.*esp_radio*wifi*os_adapter*mutex_unlock*)
    *(.text.*esp_radio*wifi*os_adapter*nvs_get_blob*)
    *(.text.*esp_radio*wifi*os_adapter*nvs_set_blob*)
    *(.text.*esp_radio*wifi*os_adapter*log_timestamp*)
    *(.text.*esp_radio*wifi*os_adapter*nvs_erase_key*)
    *(.text.*esp_radio*wifi*os_adapter*wifi_reset_mac*)
    *(.text.*esp_radio*wifi*os_adapter*task_ms_to_tick*)
    *(.text.*esp_radio*wifi*os_adapter*spin_lock_create*)
    *(.text.*esp_radio*wifi*os_adapter*wifi_int_disable*)
    *(.text.*esp_radio*wifi*os_adapter*wifi_int_restore*)
    *(.text.*esp_radio*wifi*os_adapter*wifi_create_queue*)
    *(.text.*esp_radio*wifi*os_adapter*wifi_delete_queue*)
    *(.text.*esp_radio*wifi*os_adapter*event_group_create*)
    *(.text.*esp_radio*wifi*os_adapter*event_group_delete*)
    *(.text.*esp_radio*wifi*os_adapter*get_free_heap_size*)
    *(.text.*esp_radio*wifi*os_adapter*task_yield_from_isr*)
    *(.text.*esp_radio*wifi*os_adapter*event_group_set_bits*)
    *(.text.*esp_radio*wifi*os_adapter*event_group_wait_bits*)
    *(.text.*esp_radio*wifi*os_adapter*task_get_current_task*)
    *(.text.*esp_radio*wifi*os_adapter*task_get_max_priority*)
    *(.text.*esp_radio*wifi*os_adapter*wifi_thread_semphr_get*)
    *(.text.*esp_radio*wifi*os_adapter*phy_update_country_info*)
    *(.text.*esp_radio*wifi*os_adapter*coex_schm_curr_phase_get*)
    *(.text.*esp_radio*wifi*os_adapter*coex_schm_get_phase_by_idx*)
    *(.text.*esp_radio*wifi*os_adapter*free*)
    *(.text.*esp_radio*wifi*os_adapter*rand*)
    *(.text.*esp_radio*wifi*os_adapter*malloc*)
    *(.text.*esp_radio*wifi*os_adapter*ints_on*)
    *(.text.*esp_radio*wifi*os_adapter*get_time*)
    *(.text.*esp_radio*wifi*os_adapter*ints_off*)
    *(.text.*esp_radio*wifi*os_adapter*nvs_open*)
    *(.text.*esp_radio*wifi*os_adapter*set_intr*)
    *(.text.*esp_radio*wifi*os_adapter*nvs_close*)
    *(.text.*esp_radio*wifi*os_adapter*clear_intr*)
    *(.text.*esp_radio*wifi*os_adapter*coex_deinit*)
    *(.text.*esp_radio*wifi*os_adapter*coex_enable*)
    *(.text.*esp_radio*wifi*os_adapter*env_is_chip*)
    *(.text.*esp_radio*wifi*os_adapter*coex_pti_get*)
    *(.text.*esp_radio*wifi*os_adapter*slowclk_cal_get*)
    *(.text.*esp_radio*wifi*os_adapter*coex_wifi_release*)
    *(.text.*esp_radio*wifi*os_adapter*coex_wifi_request*)
    *(.text.*esp_radio*wifi*os_adapter*coex_wifi_channel_set*)
    *(.text.*esp_radio*wifi*os_adapter*coex_register_start_cb*)
    *(.text.*esp_radio*wifi*os_adapter*coex_schm_curr_period_get*)
    *(.text.*esp_radio*wifi*os_adapter*coex_schm_flexible_period_set*)
    *(.text.*esp_radio*wifi*os_adapter*os_adapter_chip_specific7set_isr*)


    *(.text.*esp_radio*wifi*embassy*impl*embassy_net_driver*Driver*for*esp_radio*wifi*WifiDevice*hardware_address*)

    *(.text.*esp_radio*wifi*WifiController*apply_ap_config*)
    *(.text.*esp_radio*wifi*WifiController*apply_protocols*)
    *(.text.*esp_radio*wifi*WifiController*set_power_saving*)

    *(.text.*esp_radio*wifi*WifiController*as*core*ops*drop*Drop*drop*)

    *(.text.*esp_radio*wifi*WifiDeviceMode*tx_token*)

    *(.text.*esp_radio*wifi*WifiMode*current*)

    *(.text.*esp_radio*wifi*recv_cb_ap*)
    *(.text.*esp_radio*wifi*recv_cb_sta*)
    *(.text.*esp_radio*wifi*esp_wifi_send_data*)
    *(.text.*esp_radio*wifi*decrement_inflight_counter*)

    *(.text.__esp_radio_vTaskDelay)
    *(.text.__esp_radio_esp_event_post)
    *(.text.__esp_radio_esp_fill_random)
    *(.text.__esp_radio_esp_timer_get_time)
    *(.text.__esp_radio_gettimeofday)

    *(.text.unlikely.__esp_radio_fclose)
    *(.text.unlikely.__esp_radio_fgets)
    *(.text.unlikely.__esp_radio_fopen)
    *(.text.unlikely.__esp_radio_fwrite)
    *(.text.unlikely.__esp_radio_strrchr)

    *(.text.__esp_radio_puts)
    *(.text.__esp_radio_putchar)
    *(.text.__esp_radio_sleep)
    *(.text.__esp_radio_strdup)
    *(.text.__esp_radio_usleep)

    *(.text.WIFI_MAC)
    *(.text.WIFI_PWR)

    

    *(.text.*num_traits*cast*FromPrimitive*from_i32*)
    *(.text.*esp_radio*wifi*WifiController*clear_events*)
    *(.text.*esp_radio*compat*mutex*mutex_create*)
    *(.text.*esp_radio*compat*semaphore*sem_create*)

} > ROTEXT
