[package]
name = "smoltcp"
version = "0.12.0"
edition = "2021"
rust-version = "1.81"

[dependencies]
#console = { path = "../../console" }
#defmt = { version = "0.3.10", optional = true, features = ["ip_in_core"] }
#defmt = { version = "1.0.1", optional = true }
defmt = { version = "1.0.1", optional = true, features = ["ip_in_core"] }
log = { version = "0.4.14", optional = true }
#allocator-api2 = { path = "../../allocator-api2", features = ["alloc"] }
allocator-api2 = { version = "0.3.0", default-features = false, features = ["alloc"] }
linear-map = { path = "../linear-map" }
managed = { path = "../managed", default-features = false }
byteorder = { version = "1.0", default-features = false }
bitflags = { version = "1.0", default-features = false }

[features]
# we use allocato-api2 wit 'alloc', but not used this 'alloc' feature
# since we use ManagedSlice in SocketSet with fixed number of slots
alloc = ["managed/alloc", "defmt?/alloc"]
"medium-ethernet" = ["socket"]

"proto-ipv4" = []
"proto-dhcpv4" = ["proto-ipv4"]
"proto-ipv6" = []

"multicast" = []

"socket" = []
"socket-udp" = ["socket"]
"socket-icmp" = ["socket"]
"socket-dhcpv4" = ["socket", "medium-ethernet", "proto-dhcpv4"]

"packetmeta-id" = []

"async" = []

default = [
    "medium-ethernet",
    "proto-ipv4", "proto-dhcpv4",
    "socket-udp", "socket-dhcpv4", "socket-icmp",
    "async", "packetmeta-id",
]

# Private features
# Features starting with "_" are considered private. They should not be enabled by
# other crates, and they are not considered semver-stable.

"_proto-fragmentation" = []