[build]
target = "riscv32imc-unknown-none-elf"
#target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core", "alloc"]

[patch.crates-io]
esp-alloc = { git = "https://github.com/gobftald/esp-hal.git", branch = "patches" }
esp-config = { git = "https://github.com/gobftald/esp-hal.git", branch = "patches" }
esp-hal = { git = "https://github.com/gobftald/esp-hal.git", branch = "patches" }
esp-sync = { git = "https://github.com/gobftald/esp-hal.git", branch = "patches" }

[alias]
bs = "build --target xtensa-esp32s3-none-elf --features esp32s3"
bc = "build --target riscv32imc-unknown-none-elf --features esp32c3"
