[package]
name = "esp-radio"
version = "0.17.0"
edition = "2024"

[lib]
test = false
bench = false

[dependencies]
#defmt = { version = "0.3.10", optional = true }
# Logging interfaces, they are mutually exclusive so they need to be behind separate features.
defmt = { version = "1.0.1", optional = true }
log-04 = { package = "log", version = "0.4.27", optional = true }

esp-hal = { version = "1.0.0", default-features = false, features = ["requires-unstable"] }
cfg-if = "1.0.0"
esp-alloc = { version = "0.9.0", default-features = false, optional = true }
esp-config = { version = "0.6.1" }
esp-metadata-generated   = { version = "0.3.0" }
#allocator-api2 = { path = "../../allocator-api2"}
allocator-api2 = { version = "0.3.0", default-features = false, features = ["alloc"] }
esp-wifi-sys-esp32c3 = {version = "0.1.0", optional = true }
num-derive = { version = "0.4.2" }
num-traits = { version = "0.2.19", default-features = false }
critical-section = { version = "1.2.0" }
enumset   = { version = "1.1.6", default-features = false, optional = true }
smoltcp = { path = "../../smoltcp/smoltcp", default-features = false, features = ["medium-ethernet"], optional = true }
embassy-net-driver = { version = "0.2.0", optional = true }
portable-atomic = { version = "1.5", default-features = false }
portable_atomic_enum = { version = "0.3.1", features = ["portable-atomic"] }
esp-sync = "0.1.0"
esp-radio-rtos-driver = "0.2.0"
esp-phy = { path = "../esp-phy/" }

[build-dependencies]
esp-config = { version = "0.6.1", features = ["build"] }
esp-metadata = "0.10.0"
esp-metadata-generated = { version = "0.3.0", features = ["build-script"] }

[features]
#default = ["builtin-scheduler", "esp-alloc"]
default = ["esp-alloc"]

# Target the ESP32-C3.
esp32c3 = [
  "esp-hal/esp32c3",
  "dep:esp-wifi-sys-esp32c3",
  "esp-phy/esp32c3",
]

## Use `esp-alloc` for dynamic allocations.
##
## If you opt-out you need to provide implementations for the following functions:
## - `pub extern "C" fn esp_wifi_free_internal_heap() -> usize`
## - `pub extern "C" fn esp_wifi_allocate_from_internal_ram(size: usize) -> *mut u8`
## - `pub extern "C" fn esp_wifi_deallocate_internal_ram(ptr: *mut u8)`
esp-alloc = ["dep:esp-alloc"]

## Logs the WiFi logs from the driver at log level info (needs a nightly-compiler)
sys-logs = ["esp-wifi-sys-esp32c3?/sys-logs"]

## Use builtin scheduler
#builtin-scheduler = ["esp-hal/__esp_wifi_builtin_scheduler"]
# we don't use SW interrupts yet, so we don't want 'skip' Software interrupt 2
builtin-scheduler = []

#! ### Wireless Feature Flags

## Enable WiFi support
wifi = ["dep:embassy-net-driver", "dep:enumset"]

## Provide implementations of smoltcp traits
# don't use smoltcp from here, but via embassy_net
smoltcp = ["dep:smoltcp"]

## Enable WiFi channel state information. See [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_wifi.html#_CPPv4N18wifi_init_config_t10csi_enableE)",
csi = []

defmt = [
  "dep:defmt",
  "esp-hal/defmt",
  "smoltcp?/defmt",
  "esp-alloc/defmt",
  "esp-wifi-sys-esp32c3?/defmt",
  "enumset?/defmt",
  #"allocator-api2/defmt",
  "embassy-net-driver/defmt",
]
